dist: trusty
language: java
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
jobs:
  include:
    - stage: "Test"
      script: ./gradlew test
      jdk: oraclejdk8
    - script: ./gradlew test
      jdk: oraclejdk9
    - script: ./gradlew test
      jdk: oraclejdk11
    - stage: "Static Analysis"
      script: ./gradlew staticAnalysis
      jdk: oraclejdk8
    - script: ./gradlew staticAnalysis
      jdk: oraclejdk9
    - script: ./gradlew staticAnalysis
      jdk: oraclejdk11
